sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

mysql: &mysql
  adapter: mysql2
  username: root
  password:
  database: secure_santa_<%= Rails.env %>

postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: secure_santa_<%= Rails.env %>
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "postgresql" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

development:
          adapter: postgresql
          database: secure_santa_dev
          host: localhost

test:
          adapter: postgresql
          database: secure_santa_test
          host: localhost

production:
          adapter: postgresql
          database: secure_santa_prod
          host: localhost
